apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: 
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
      app: myapp

    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu

  replicas: 3


  selector: 
    matchLabels:
      app: myapp